previews:
  generation: automatic

services:
  - type: web
    runtime: docker
    name: poker
    repo: https://github.com/MPopovych/TeamPointingPoker.git
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 60
      targetCPUPercent: 60
